# Generated by Django 4.1.7 on 2023-03-27 13:24

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=100, unique=True)),
                ("year", models.IntegerField()),
                ("url", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField()),
            ],
        ),
    ]
