# Generated by Django 4.1.7 on 2023-03-27 13:27

from django.apps.registry import Apps
from django.db import migrations
from django.db.backends.base.schema import BaseDatabaseSchemaEditor


def create_sample_games(apps: Apps, schema_editor: BaseDatabaseSchemaEditor) -> None:
    """Create sample game objects in database."""
    serialized_games = [
        {
            "id": 162886,
            "title": "Spirit Island",
            "year": 2017,
            "url": "https://boardgamegeek.com/boardgame/162886/spirit-island",
            "description": "Island Spirits join forces using elemental powers to defend their home from invaders.",
        },
        {
            "id": 220308,
            "title": "Gaia Project",
            "year": 2017,
            "url": "https://boardgamegeek.com/boardgame/220308/gaia-project",
            "description": "Expand, research, upgrade, and settle the galaxy with one of 14 alien species.",
        },
        {
            "id": 316554,
            "title": "Dune: Imperium",
            "year": 2020,
            "url": "https://boardgamegeek.com/boardgame/316554/dune-imperium",
            "description": "Influence, intrigue, and combat in the universe of Dune.",
        },
    ]
    Game = apps.get_model("games", "Game")
    for serialized_game in serialized_games:
        game = Game(**serialized_game)
        game.save()


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0001_initial"),
    ]

    operations = [migrations.RunPython(create_sample_games)]
