# Generated by Django 4.1.7 on 2023-03-29 09:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=100, unique=True)),
                ("url", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField()),
            ],
        ),
    ]
