# Generated by Django 4.1.7 on 2023-03-29 09:33

from django.apps.registry import Apps
from django.db import migrations
from django.db.backends.base.schema import BaseDatabaseSchemaEditor


def create_sample_games(apps: Apps, schema_editor: BaseDatabaseSchemaEditor) -> None:
    """Create sample game objects in database."""
    serialized_games = [
        {
            "id": 162886,
            "title": "Spirit Island",
            "year": 2017,
            "url": "https://boardgamegeek.com/boardgame/162886/spirit-island",
            "description": "Island Spirits join forces using elemental powers to defend their home from invaders.",
        },
        {
            "id": 220308,
            "title": "Gaia Project",
            "year": 2017,
            "url": "https://boardgamegeek.com/boardgame/220308/gaia-project",
            "description": "Expand, research, upgrade, and settle the galaxy with one of 14 alien species.",
        },
        {
            "id": 316554,
            "title": "Dune: Imperium",
            "year": 2020,
            "url": "https://boardgamegeek.com/boardgame/316554/dune-imperium",
            "description": "Influence, intrigue, and combat in the universe of Dune.",
        },
    ]
    Game = apps.get_model("games", "Game")
    for serialized_game in serialized_games:
        game = Game(**serialized_game)
        game.save()


def create_sample_categories(apps: Apps, schema_editor: BaseDatabaseSchemaEditor) -> None:
    """Create sample category objects in database."""
    serialized_categories = [
        {
            "id": 1010,
            "title": "Fantasy",
            "url": "https://boardgamegeek.com/boardgamecategory/1010/fantasy",
            "description": "Fantasy games are those that have themes and scenarios that exist in a fictional world...",
        },
        {
            "id": 1015,
            "title": "Civilization",
            "url": "https://boardgamegeek.com/boardgamecategory/1015/civilization",
            "description": "Civilization games often have players developing and managing a society of people...",
        },
        {
            "id": 1086,
            "title": "Territory Building",
            "url": "https://boardgamegeek.com/boardgamecategory/1086/territory-building",
            "description": "Territory Building games have the players establish and/or amass control over a ...",
        },
    ]
    Categories = apps.get_model("games", "Category")
    for serialized_game in serialized_categories:
        game = Categories(**serialized_game)
        game.save()


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0002_category"),
    ]

    operations = [migrations.RunPython(create_sample_games), migrations.RunPython(create_sample_categories)]
